### ISSUE TITLE
Incorrect path to index.php (absolute)

### ISSUE THREAD

**Issue by danielperna84** [rohankapoorcom/zm-py#12]
With HASS 0.79 the ZoneMinder component has broken for me. The issue seems to be [here](https://github.com/rohankapoorcom/zm-py/blob/961ac830c5b391ab6f051afad083e88ecbb30714/zoneminder/zm.py#L43). The path to `index.php` is absolute, which does not work when a reverse proxy is being used. Removing the prepended `/` fixed the issue for me.

**Comment by rohankapoorcom** [comment]
@danielperna84 can you test out a branch for me?

https://github.com/rohankapoorcom/zm-py/tree/login-path-errors

If you can copy down the files from that branch (likely via git), you should be able to run ` pip install . && hass --skip-pip` if you are inside the `zm-py` folder and are inside your homeassistant virtualenvironment.

**Comment by rohankapoorcom** [comment]
I got confirmation from @yajrendrag in https://github.com/home-assistant/home-assistant/issues/16829 that my fix that branch solves the problem. I'm going to get this merged and packaged.
