### ISSUE TITLE
Report when a monitor is in an error state

### ISSUE THREAD

**Issue by mnoorenberghe** [rohankapoorcom/zm-py#20]
Right now there's no way to know that a monitor is in an error state while having the desired function e.g. camera offline. On the ZM dashboard this is shown in red. IMO ZMSensorMonitors's status should change when a monitor is in an error state but I would also be fine with a separate sensor for this and I can combine them with a template sensor.

**Comment by mnoorenberghe** [comment]
Hmm… I thought I had found it years ago but I don't see it right now. Upstream ZoneMinder would probably take a patch though.

/zm/api/host/daemonCheck.json would be useful to expose to know if the zoneminder process is running at all but that's not per-monitor.

**Comment by mnoorenberghe** [comment]
Found it:
/zm/api/monitors/daemonStatus/id:1/daemon:zmc.json (substitute the appropriate monitor ID for "1")

Ref: https://github.com/ZoneMinder/ZoneMinder/issues/799#issuecomment-108996075

I'll get that added to ZM docs.

**Comment by mnoorenberghe** [comment]
I'm documenting it in https://github.com/ZoneMinder/zoneminder/pull/2278

**Comment by rohankapoorcom** [comment]
Nice thanks! Pull requests are welcome if you'd like to take care of this yourself, otherwise I will get to it when I next have time :)
