### ISSUE TITLE
ZM 1.32 not able to login

### ISSUE THREAD

**Issue by fripsy** [rohankapoorcom/zm-py#21]
I upgraded ZM to version 1.32 and HA is not able to login, not much in the debug log:
`
2018-10-29 19:40:24 ERROR (SyncWorker_4) [zoneminder.zm] Connection error logging into ZoneMinder
2018-10-29 19:40:24 ERROR (MainThread) [homeassistant.setup] Setup failed for zoneminder: Component failed to initialize.
`
Have they changed the login procedure?

**Comment by fripsy** [comment]
I think this is an issue with my ZM setup, I will investigate further and will close this issue for now.

**Comment by rohankapoorcom** [comment]
Looks like they changed the API login approach in 1.32. https://zoneminder.readthedocs.io/en/stable/api.html#a-deeper-dive-into-the-login-process

The old way should still work, but we should try to support the new way as well. I'll file an issue for that.
