### ISSUE TITLE
zoneminder 1.36.x - runstate active non recognized

### ISSUE THREAD

**Issue by CyberGuerro** [rohankapoorcom/zm-py#54]
With 1.36 version developer have fixed states **IsActive** property becoming it to int (no more string) so **run_state.py** has to be changed at line 31

Old:
            if int(state["Id"]) == self._state_id:
                # yes, the ZM API uses the *string* "1" for this...
                **return state["IsActive"] == "1"**

New:
            if int(state["Id"]) == self._state_id:
                **return state["IsActive"] == 1**

**Comment by nabbi** [comment]
@rohankapoorcom once merged, can we please get a release version bump so we can increment the HA package deps ?

**Comment by nabbi** [comment]
fixed in v0.5.3
