### ISSUE TITLE
Support Monitors that are in MonitorState None

### ISSUE THREAD

**Issue by rohankapoorcom** [rohankapoorcom/zm-py#7]
Currently zm-py ignores monitors that are in MonitorState None. We probably shouldn't do that.

This was originally reported in https://github.com/home-assistant/home-assistant/issues/16829#issuecomment-424111690 by @dshokouhi

**Comment by dshokouhi** [comment]
@rohankapoorcom feel free to tag me to test the changes :)

**Comment by dshokouhi** [comment]
@rohankapoorcom looks good to me, HA booted up without error and all expected entities were added.

**Comment by rohankapoorcom** [comment]
@dshokouhi Awesome, great to hear. I'll get this merged in and published to pypi and will then PR Home Assistant to bump the lib. Thanks for testing!

**Comment by dshokouhi** [comment]
Thank you so much for the speedy response :)
